trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

# stages:
# - stage: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     # - script: echo $PATH
#     - bash: echo Build FirstJob


steps:
- script: |
    bash -c "echo 'Hello from Bash'"
  displayName: 'Run Bash script'