trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

# stages:
# - stage: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     # - script: echo $PATH
#     - bash: echo Build FirstJob


steps:
- script: |
    if ($env:SHELL) {
      echo "Using shell: $env:SHELL"
    } else {
      echo "No SHELL environment variable found"
    }
  displayName: 'Check Shell Environment'