trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

# stages:
# - stage: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     # - script: echo $PATH
#     - bash: echo Build FirstJob


steps:
-     script: |
        "hostname && pwd"
      displayName: "Run bash command with Unix-style path" 