trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

variables:
  PATH: $(PATH):C:\Program Files\Git\bin\

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo $PATH
    - bash: echo Build FirstJob