trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

# stages:
# - stage: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     # - script: echo $PATH
#     - bash: echo Build FirstJob


steps:
- script: echo %ComSpec%
  displayName: 'Check Command Prompt shell'