trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

# stages:
# - stage: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     # - script: echo $PATH
#     - bash: echo Build FirstJob

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: |
        export PATH="/c/Program Files/Git/bin:$PATH"
        echo "Build FirstJob"
      displayName: 'Run Build Script in Bash'