trigger:
- main

pool:
  name: NakSriniAgentPool
  vmImage: yyxxzz

steps:
-     script: |
        "C:\Program Files\Git\bin\bash.exe" -c "cd /c/Program\ Files/Git/bin && pwd"
      displayName: "Run bash command with Unix-style path" 